### ISSUE TITLE
panic: chacha20poly1305: invalid buffer overlap

### ISSUE THREAD

**Issue by SiJinmin** [shadowsocks/go-shadowsocks2#102]
服务端启动一会以后就发生了这个错误

**Comment by xqdoo00o** [comment]
使用Go 1.10.3 遇到相同问题。
panic: chacha20poly1305: invalid buffer overlap

goroutine 6 [running]:
golang.org/x/crypto/chacha20poly1305.(*chacha20poly1305).open(0xc420293240, 0xc4200c4000, 0x0, 0x10000, 0x673ea0, 0xc, 0x80, 0xc4200c4020, 0x33, 0xffe0, ...)
	/root/go/src/golang.org/x/crypto/chacha20poly1305/chacha20poly1305_amd64.go:77 +0x4d3
golang.org/x/crypto/chacha20poly1305.(*chacha20poly1305).Open(0xc420293240, 0xc4200c4000, 0x0, 0x10000, 0x673ea0, 0xc, 0x80, 0xc4200c4020, 0x33, 0xffe0, ...)
	/root/go/src/golang.org/x/crypto/chacha20poly1305/chacha20poly1305.go:85 +0x103
github.com/shadowsocks/go-shadowsocks2/shadowaead.Unpack(0xc4200c4000, 0x10000, 0x10000, 0xc4200c4000, 0x53, 0x10000, 0x59c380, 0xc4200584c0, 0x0, 0xc420043e40, ...)
	/root/go/src/github.com/shadowsocks/go-shadowsocks2/shadowaead/packet.go:56 +0x225
github.com/shadowsocks/go-shadowsocks2/shadowaead.(*packetConn).ReadFrom(0xc4200584c0, 0xc4200c4000, 0x10000, 0x10000, 0x1, 0x10000, 0x0, 0x0, 0x0)
	/root/go/src/github.com/shadowsocks/go-shadowsocks2/shadowaead/packet.go:91 +0xec
main.udpRemote(0x7ffc2845de61, 0x3, 0xc42000c140)
	/root/go/src/github.com/shadowsocks/go-shadowsocks2/udp.go:137 +0x267
created by main.main
	/root/go/src/github.com/shadowsocks/go-shadowsocks2/main.go:155 +0x92a

**Comment by xqdoo00o** [comment]
Use either 1.10.3 or 1.11 rc1, I always get this error.
panic: chacha20poly1305: invalid buffer overlap

goroutine 6 [running]:
golang.org/x/crypto/chacha20poly1305.(*chacha20poly1305).open(0xc0000182a0, 0xc0000ba000, 0x0, 0x10000, 0x6c10e0, 0xc, 0x80, 0xc0000ba020, 0x33, 0xffe0, ...)
        /root/go/src/golang.org/x/crypto/chacha20poly1305/chacha20poly1305_amd64.go:77 +0x4aa
golang.org/x/crypto/chacha20poly1305.(*chacha20poly1305).Open(0xc0000182a0, 0xc0000ba000, 0x0, 0x10000, 0x6c10e0, 0xc, 0x80, 0xc0000ba020, 0x33, 0xffe0, ...)
        /root/go/src/golang.org/x/crypto/chacha20poly1305/chacha20poly1305.go:85 +0x103
github.com/shadowsocks/go-shadowsocks2/shadowaead.Unpack(0xc0000ba000, 0x10000, 0x10000, 0xc0000ba000, 0x53, 0x10000, 0x5a7f40, 0xc000010540, 0x0, 0x2, ...)
        /root/go/src/github.com/shadowsocks/go-shadowsocks2/shadowaead/packet.go:56 +0x225
github.com/shadowsocks/go-shadowsocks2/shadowaead.(*packetConn).ReadFrom(0xc000010540, 0xc0000ba000, 0x10000, 0x10000, 0x1, 0x10000, 0x0, 0x0, 0x0)
        /root/go/src/github.com/shadowsocks/go-shadowsocks2/shadowaead/packet.go:91 +0xec
main.udpRemote(0x7ffe81c03e59, 0x3, 0xc00000c140)
        /root/go/src/github.com/shadowsocks/go-shadowsocks2/udp.go:137 +0x25c
created by main.main
        /root/go/src/github.com/shadowsocks/go-shadowsocks2/main.go:155 +0x914

**Comment by xqdoo00o** [comment]
I think it's a compatible issue with ss-android.
I use libev version on the same machine with same port and encrypt method, the ss-android connection 
test passed, and Tx/Rx shows normally.
but when I use go version,  the ss-android connection test never passed, and Tx/Rx always shows 0kB, the server log below (looks like none connection would success set up)
```
2018/08/22 15:30:33 udp.go:135: listening UDP on :80
2018/08/22 15:30:33 tcp.go:101: listening TCP on :80
panic: chacha20poly1305: invalid buffer overlap
...
```
ss-android version: 4.5.7,
network: China Unicom 4g,
go version: 1.11 rc1.

**Comment by riobard** [comment]
Please try v0.0.10 https://github.com/shadowsocks/go-shadowsocks2/releases/tag/v0.0.10

**Comment by xqdoo00o** [comment]
Still the same errors, except for AES_GCM.
Maybe the release built with go 1.10.3?

**Comment by lixin9311** [comment]
It's a feature introduced in go 1.11 to check the overlapping of the buffers upon decryption.
For more information, see https://github.com/shadowsocks/go-shadowsocks2/issues/95
Fixed in https://github.com/shadowsocks/go-shadowsocks2/pull/109
