### ISSUE TITLE
A bug found in packet.go

### ISSUE THREAD

**Issue by JMVoid** [shadowsocks/go-shadowsocks2#103]
A bug was found in udp relay function. 
in packet.go, line 83
	return len(b), addr, err
the return variable of reading byte length should be len(bb) but not len(b). the b is input variable length come from buf (buf := make([]byte, udpBufSize)). so the return reading byte length always  65536.

**Comment by TongxiJi** [comment]
yes, a biiiiiiiiig bug.

**Comment by lixin9311** [comment]
Thank you for pointing it out
Fixed in https://github.com/shadowsocks/go-shadowsocks2/pull/109
