### ISSUE TITLE
More than one connecting and other encrypt method

### ISSUE THREAD

**Issue by WeFenFinit** [shadowsocks/go-shadowsocks2#104]
Server side got crush while I trying connect more than one device. While connect CHACHA20 on android server side got crush similarly.
Server - Aruba, Ubuntu 18.04 LTS, kernel 4.15, BBR
Client0 - Windows 10 with GO-shadowsocks2
Client1 - Android 5.0.1, LG h522y, shadowsocks-android-4.5.7

**Comment by xqdoo00o** [comment]
Did you open Dns forward option in ss-android? If so, close it and it will be ok. see more https://github.com/shadowsocks/go-shadowsocks2/issues/102#issuecomment-414942262
