### ISSUE TITLE
Out of memory upon installation

### ISSUE THREAD

**Issue by sgon00** [shadowsocks/go-shadowsocks2#105]
When I run 

```
go get -u -v github.com/shadowsocks/go-shadowsocks2
```

It outputs:

```
github.com/shadowsocks/go-shadowsocks2 (download)
# cd .; git clone https://github.com/shadowsocks/go-shadowsocks2 /home/user/go/src/github.com/shadowsocks/go-shadowsocks2
Cloning into '/home/user/go/src/github.com/shadowsocks/go-shadowsocks2'...
fatal: Out of memory, malloc failed (tried to allocate 1048576000 bytes)
fatal: Not a git repository: '/home/user/go/src/github.com/shadowsocks/go-shadowsocks2/.git'
package github.com/shadowsocks/go-shadowsocks2: exit status 12
```

Do I do anything wrong? Why does it need 1GB memory for such a tool? 

Thanks a lot.

**Comment by riobard** [comment]
Obviously it's not the caused by `go-ss2`. You haven't even finished cloning the repository. Something is wrong with your Go toolchain.

**Comment by sgon00** [comment]
Sorry that it's my mistake. It's actually not a problem of my go and it's a problem of my `.gitconfig`. I copied my laptop's `.gitconfig` to my server and it has `postBuffer = 1000M`. I was so stupid and have no idea why I did successfully `go get` many projects before...
