### ISSUE TITLE
[New Feature Request] Allowing go-shadowsocks2 server's outgoing request using socks5 proxy

### ISSUE THREAD

**Issue by aeroxy** [shadowsocks/go-shadowsocks2#107]
Allowing go-shadowsocks2 server's outgoing request using socks5 proxy would effectively create shadowsocks proxychains which is harder to detect.

**Comment by nadoo** [comment]
you can try: https://github.com/nadoo/glider 
based on go-shadowsocks2

**Comment by nadoo** [comment]
You can try [glider](https://github.com/nadoo/glider), based on go-shadowsocks2.

**Comment by riobard** [comment]
Why? It's simpler and faster to setup NAT using iptables on jumping machines instead of deploying shadowsocks servers on them.

**Comment by aeroxy** [comment]
@nadoo thx, I will take a look.

@riobard because this is the first time I've heard about NAT...
