### ISSUE TITLE
请问日志文件在哪，老掉线程

### ISSUE THREAD

**Issue by LsnmxNB** [shadowsocks/go-shadowsocks2#110]
centos 7下开机/etc/rc.d/rc.local
/home/go/bin/go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:nbXX@:10080 -verbose
老掉线程，ps aux 发现线程不见了。难怪开心不了
@riobard

**Comment by lixin9311** [comment]
最后加上 `> /path/to/log 2>&1` 就行了

**Comment by LsnmxNB** [comment]
最后加上 > /path/to/log 2>&1  日志保存在哪个位置，谢谢

**Comment by LsnmxNB** [comment]
@lixin9311

**Comment by lixin9311** [comment]
/path/to/log 改成你想要的日志路径
