### ISSUE TITLE
Multiuser Support

### ISSUE THREAD

**Issue by hjdo** [shadowsocks/go-shadowsocks2#111]
这个golang版本能不能配置多用户，不知道怎么能按照[这个配置示例](https://github.com/shadowsocks/shadowsocks/wiki/Configure-Multiple-Users)进行配置，想使用shadowsocks-manager这个项目。
感谢开发者！

**Comment by riobard** [comment]
We do not currently support multiple port/user. However, you can always start multiple server instances (at the cost of memory of course).

**Comment by nbvghost** [comment]
将来会不会支持多用户？

**Comment by riobard** [comment]
加入计划吧
