### ISSUE TITLE
values of cipher (or encrypt_method) should be named similar to other implementations

### ISSUE THREAD

**Issue by xiazuojie** [shadowsocks/go-shadowsocks2#115]
For example, encrypt method known as 'chacha20-ietf-poly1305' in other implementations (and most GUI clients) is named 'AEAD_CHACHA20_POLY1305' here.
We should avoid this unnecessary confusion and use the same names.

**Comment by riobard** [comment]
You got it backwards. The spec is now following IANA AEAD registry. Read http://shadowsocks.org/en/spec/AEAD-Ciphers.html

**Comment by xiazuojie** [comment]
I see. So other implementations need to be changed to use the new names.
How about the SIP002 URI scheme? According to spec, userinfo should be base64 encoded. This implementation is not doing that?
And why 'encrypt method' is called 'cipher' here?

**Comment by riobard** [comment]
> So other implementations need to be changed to use the new names.

Yes, if they are to be compliant with the official spec.

> How about the SIP002 URI scheme? According to spec, userinfo should be base64 encoded. This implementation is not doing that?

No, this implementation does not yet support SIP002. SIP002 is mostly for GUI clients, but base64 encoding makes it harder to config manually via command line.

> And why 'encrypt method' is called 'cipher' here?

Because in English we say "pork" instead of "pig meat".
