### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by fortuna** [shadowsocks/go-shadowsocks2#121]
We are [doing it in outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server/pull/6), with a number of benefits:
- Simplifies development
  - You can clone the repository anywhere. No need to worry about the Go tree and you can now have many clients working on the repo.
  - You can work on your personal forked repository without having to [rewrite the import paths](https://github.com/riobard/go-shadowsocks2/blob/be6a149ce736946d8bc7dbe3b56f292a2aa0dc07/main.go#L13) or hack the Go tree
- Allows for reproducible builds, since the dependencies are locked.

You can learn more on Go modules here: https://github.com/golang/go/wiki/Modules

**Comment by riobard** [comment]
I'll wait till Go modules graduate from "experimental" phase hopefully in Go 1.12 :)

**Comment by riobard** [comment]
Closed by #134
