### ISSUE TITLE
passad and @

### ISSUE THREAD

**Issue by jicki** [shadowsocks/go-shadowsocks2#123]
shadowsocks2 -c 'ss://AEAD_CHACHA20_POLY1305:your-password@[server_address]:8488' \
    -verbose -socks :1080

```
my passwd is   :  1234@22###

shadowsocks2 -c 'ss://AEAD_CHACHA20_POLY1305:1234@22###@192.168.168.100:8488' \
    -verbose -socks :1080
```

error logs

```
tcp.go:69: failed to connect to server : dial tcp: missing address
```

**Comment by Hench10** [comment]
密码建议使用不会被URL转义的字符

**Comment by riobard** [comment]
This is the inherent problem of the URL scheme. Either use escaped strings or avoid problematic characters.
