### ISSUE TITLE
iv或者salt的特征

### ISSUE THREAD

**Issue by beyondkmp** [shadowsocks/go-shadowsocks2#125]
1. 每个连接都先发iv或者salt，而不是iv+data一起发。这样iv和salt的长度是固定的，是不是特征就比较明显了？
2. 效率方面，每次先发iv或者salt,都要浪费一个rtt,这样握手速度方面也会变慢。

**Comment by riobard** [comment]
You should discuss protocol design issues here instead https://github.com/shadowsocks/shadowsocks-org/issues

This repo should only be about the particular implementation.
