### ISSUE TITLE
Parsing error "too many colons" on win64

### ISSUE THREAD

**Issue by RedKage** [shadowsocks/go-shadowsocks2#131]
There seems to be an issue with the win64 build. I get a "too many colons in address" error wether in server or client mode.
I have the same error with precompiled version v0.0.11 and v0.0.9 and also building the binary from sources ( commit a31551f )

In server mode
`>shadowsocks2-win64 -s 'ss://AEAD_CHACHA20_POLY1305:pass@:8888' -verbose`

> 2019/03/11 11:06:21 tcp.go:97: failed to listen on 'ss://AEAD_CHACHA20_POLY1305:pass@:8888': listen tcp: address 'ss://AEAD_CHACHA20_POLY1305:pass@:8888': too many colons in address
2019/03/11 11:06:21 udp.go:126: UDP remote listen error: listen udp: address 'ss://AEAD_CHACHA20_POLY1305:pass@:8888': too many colons in address

In client mode
`>shadowsocks2-win64 -c 'ss://AEAD_CHACHA20_POLY1305:pass@my.server:8888' -verbose -socks :8080 -u`

> 2019/03/11 11:08:47 tcp.go:13: SOCKS proxy :8080 <-> 'ss://AEAD_CHACHA20_POLY1305:pass@my.server:8888'
2019/03/11 11:08:47 udp.go:81: UDP server address error: address 'ss://AEAD_CHACHA20_POLY1305:pass@my.server:8888': too many colons in address

I don't have any issue from an Unix box.

**Comment by riobard** [comment]
Try double quotes.

**Comment by RedKage** [comment]
/facepalm
Yes the issue was with the quotes! I've been doing too much unix these days!

Thanks riobard, it works fine on Windows!

**Comment by sevenmostar** [comment]
shadowsocks2-win64 -s "ss://AEAD_CHACHA20_POLY1305:pass@:8888" -verbose
