### ISSUE TITLE
Multi interface ip(alias ip) situation output only eth0 IP not eth0:0...

### ISSUE THREAD

**Issue by dhpark21** [shadowsocks/go-shadowsocks2#132]
Hi
 I have many ip of one interface card(Centos 7) as like below
 eth0 10.10.10.10
 eth0:0 10.10.10.11
 eth0:1 10.10.10.12
 eth0:2 10.10.10.13

but, if i connect 10.10.10.12 then all packet's are output on 10.10.10.10, not 10.10.10.12
 how can i output packet to client request ip (of request port)
 ex)
 8081 port 10.10.10.11 <-> client A
 8082 port 10.10.10.12 <-> client B
 8083 port 10.10.10.13 <-> client C

Thanks

**Comment by hagolo** [comment]
Hello,
Also still didn’t found the solution ...

**Comment by riobard** [comment]
Policy routing.
