### ISSUE TITLE
是否可以考虑添加对SSR的兼容模式？

### ISSUE THREAD

**Issue by galaxy001** [shadowsocks/go-shadowsocks2#139]
目前一些机场主会认为SSR的`auth_aes128_md5`等HTTP混淆更安全，强行推SSR连接模式。
这里面可能确实有经验性的社会工程学测试结果。

所以，能否考虑添加一个兼容模式，用来连接SSR的服务端？

参考实现：
<https://github.com/shadowsocksrr/shadowsocksr-libev/commits/Akkariiin/develop>
<https://github.com/shadowsocksrr/shadowsocksr/tree/akkariiin/Experimental>

我测试发现SSRR客户端可以连接SSR服务端，就列了时间上较新的SSRR。

**Comment by riobard** [comment]
No. If you want obfuscation, look for some plugins.
