### ISSUE TITLE
support AES-256-CFB Cipher ?

### ISSUE THREAD

**Issue by LockGit** [shadowsocks/go-shadowsocks2#156]
linux system 

```bash
go-shadowsocks2 -s 'ss://AES-256-CFB:password@:18282' -verbose
```
does not support AES-256-CFB Cipher server ？

when I use ss client to connect it , have some error like this:
```
tcp.go:116: failed to get target address: SOCKS error: 8
tcp.go:116: failed to get target address: SOCKS error: 8
tcp.go:116: failed to get target address: SOCKS error: 8
```

It's can't work !

**Comment by riobard** [comment]
All stream ciphers are obsoleted and will be removed soon.

**Comment by LockGit** [comment]
> All stream ciphers are obsoleted and will be removed soon.

but my mobile client only support AES-256-CFB ciphers ,  I don't know how to deal with that.

**Comment by riobard** [comment]
Most clients support AEAD ciphers now. Use another client or ask the client developer to upgrade.

**Comment by LockGit** [comment]
I am in China, You know,  I can't download any proxy tools on the appstore in China. 

at 2019-10-23 13:13:03 ， I use support AES-256-CFB ciphers server like [shadowsocks-go](https://github.com/shadowsocks/shadowsocks-go ) . Although it has been Deprecated 😭
