### ISSUE TITLE
Feature request: Support multiple processes on the same port

### ISSUE THREAD

**Issue by clementhk** [shadowsocks/go-shadowsocks2#157]
Support reuseport
See https://github.com/shadowsocks/shadowsocks-libev/issues/493

**Comment by clementhk** [comment]
Or an option like `--workers=4`

**Comment by clementhk** [comment]
https://github.com/libp2p/go-reuseport

**Comment by riobard** [comment]
There's no need for it. Unlike ss-libev, which is single-threaded, go-ss2 is multi-threaded by default. It will use all available cores to handle multiple connections.
