### ISSUE TITLE
服务端无法保存日志？以及 -key 的使用方式是怎样的？

### ISSUE THREAD

**Issue by GoGoogle** [shadowsocks/go-shadowsocks2#17]
go-shadowsocks2 -s ss://aes-128-gcm:your-password@:8488 -verbose >>ss.log
这样是不能记录日志的，该怎么处理才能记录日志到ss.log？

另外
go-shadowsocks2 -s :8488 -cipher aes-256-cfb -key LlUmH_yMgh4YNhvayBQrs6aQHBThNpWjz1yHz0U-ePA= -verbose
服务端这么使用的情况下，客户端没密码？怎么使用？

**Comment by ccsexyz** [comment]
输出的日志是往标准错误输出的,所以你应该这样重定向 blablabla 2>> logfile

**Comment by GoGoogle** [comment]
测试过了，果然可以，谢谢！
那为什么这个字符必须是2？不能换成别的

**Comment by ccsexyz** [comment]
因为2是标准错误输出这个文件描述符的值

**Comment by GoGoogle** [comment]
@ccsexyz 感谢！明白了一些。

**Comment by riobard** [comment]
`-key` 的话需要客户端也支持，比如直接使用 go-shadowsocks2 做为客户端。
