### ISSUE TITLE
Optimize memory usage with go-shadowsocks2 in bloomring for defense replay attack.

### ISSUE THREAD

**Issue by chinsyo** [shadowsocks/go-shadowsocks2#171]
Hi, go-shadowsocks2 is such a brilliant project that really inspired me.

15Mb memory limit on iOS platform is a big challenge, and I think the dependency go-shadowsocks2 bloomring module alloc about 1Mb memory to defense replay attack in client is a little bit luxurious.

Could you please change the bloomring feature to optional?

**Comment by chinsyo** [comment]
I mean add build flags for this feature, so project using go-shadowsocks2 as dependency needn't to modify the source code. :)

**Comment by chinsyo** [comment]
@riobard

**Comment by riobard** [comment]
The Bloom filter is optional, but you have to opt out by setting an environment variable. See README. 

I'm curious how do you use go-ss2 on iOS?

**Comment by chinsyo** [comment]
> I'm curious how do you use go-ss2 on iOS?

FYI.
https://github.com/Jigsaw-Code/outline-go-tun2socks
https://github.com/eycorsican/go-tun2socks/tree/v1.16.0/proxy/shadowsocks

**Comment by riobard** [comment]
I see. Since you can opt out of Bloom filters, I assume this issue is now resolved. Feel free to reopen if there's anything else you have in mind.
