### ISSUE TITLE
How to config ShadowRocket on iOS to connect to go-shadowsocks2 at server side

### ISSUE THREAD

**Issue by sincos2007** [shadowsocks/go-shadowsocks2#172]
How to config ShadowRocket on iOS to connect to go-shadowsocks2 at server side?

Thanks

**Comment by riobard** [comment]
It's a Shadowrocket question and I don't see any difference from connecting to any shadowsocks server. Only ask questions specific to go-shadowsocks2 here.

**Comment by sincos2007** [comment]
I only want to know is it possible to use go-ss2 in ios.

Thanks
