### ISSUE TITLE
Android app with http proxy.

### ISSUE THREAD

**Issue by ingnelson** [shadowsocks/go-shadowsocks2#173]
Hello.

Is there a way to use this project on Android ? I really would like to use it on my Android as VPN to create a tunnel like VPN.

1)Install the go-shadowsocks2 on a VPS or on HEROKU website .
2) use a apk app on Android and have the http proxy option and the option to use a http header like : 

GET http://www.example.com http/1.1

Can somebody do it , please ?

**Comment by justlovediaodiao** [comment]
It's compatible with shadowsocks. You can install the go-shadowsocks2 on your VPS and use a shadowsocks app on Android.

**Comment by ingnelson** [comment]
@justlovediaodiao go-shadowsocks2 work fine, but i am looking a way to create a showsocks that can send a  send a " Request-Line " with " GET " then there is a ID (maybe it is the user and pass encode ) and then there must be a allowed websites by the firewall or allow domain by the firewall encode ( note: that domain or website it is not the server of the shadowsocks ) .
So i think the server should understand those parameter .

Here is a packet data i captured , you can see it with WIRESHARK program on pc https://www.wireshark.org/download.html
or online creating a free account on www.cloudshark.org/login
Attatch file:
