### ISSUE TITLE
one trick to improve performance perhaps

### ISSUE THREAD

**Issue by leewi9** [shadowsocks/go-shadowsocks2#178]
use `io.CopyBuffer` instead of `io.Copy` in the `tcp.go`

set the buffer size larger or find the optimal buffer size

**Comment by riobard** [comment]
You should not make random suggestions like this without understanding the code base or running real benchmarks. It's a waste of both your and my time.

**Comment by leewi9** [comment]
I said perhaps 

Who do you think you are?

**Comment by riobard** [comment]
Excuse me? I wrote the majority of the code base.

Your suggestion demonstrates your lack of understanding about how `io.Copy` works underneath, and apparently you did not study this code base to learn how it optimizes memory allocation.
