### ISSUE TITLE
国内无法通过go get安装

### ISSUE THREAD

**Issue by maojy** [shadowsocks/go-shadowsocks2#18]
https://ws2.sinaimg.cn/large/6f8c134agy1fdgm80h3e7j20mv07f763.jpg
下载不了需要的其它资源

**Comment by riobard** [comment]
需要翻墙

**Comment by maojy** [comment]
翻墙确实能装上，但是我装这个软件就是为了做客户端翻墙的，这就有点尴尬了，我要先装个别的软件翻墙了才能再装上这个

**Comment by ccsexyz** [comment]
建议提供编译好的可执行文件

**Comment by riobard** [comment]
这没办法。GitHub 也可能分分钟被墙的。用 Go 的人都有这个问题。

Pre-release binary 在我自己的 fork 上有 https://github.com/riobard/go-shadowsocks2/releases

这边还暂时没有提供

**Comment by ccsexyz** [comment]
主要是 golang.org 被墙了很僵,github 其实还好, 一般被墙也是间歇性的

**Comment by byeblack** [comment]
我所在地区github顶多只能看看，想git pull就不可能，下载也就0-10kb/s...
