### ISSUE TITLE
tcp 连接能改成 net.TCPListener 吗？

### ISSUE THREAD

**Issue by yjsslab** [shadowsocks/go-shadowsocks2#19]
因为 net.Listener 没法 SetDeadline，而且应该加上这个 Deadline 配置参数。

**Comment by riobard** [comment]
Listener 为什么需要 deadline?

**Comment by yjsslab** [comment]
@riobard 想实现这个功能，但是 net.Listener Accept 没有deadline 会一直hang着做不到。
https://github.com/hydrogen18/stoppableListener/blob/master/listener.go

**Comment by riobard** [comment]
你用自己的 Listener Accept() 进来，在用 core.StreamConnCipher.StreamConn 包一下就好了。

**Comment by yjsslab** [comment]
好吧，原来就是不想改太多。
刚看到服务器端这个报错日志：
failed to accept: accept tcp [::]:443: accept4: too many open files
 nofile 已经够大了，51200, 是不是设个 timeout 能解决？

**Comment by riobard** [comment]
先看看没断开的连接是什么状态吧

**Comment by riobard** [comment]
@yjsslab 试下最新版，解决了

**Comment by yjsslab** [comment]
@riobard 嗯，好像是解决了.
