### ISSUE TITLE
error: write udp sendto: no route to host

### ISSUE THREAD

**Issue by Ehco1996** [shadowsocks/go-shadowsocks2#192]
**Describe the bug**
I want to test udp tunnel and proxy ,with iperf3 , but failed with this "sendto: no route to host"

**To Reproduce**

1. run iperf3 server `iperf3 -s`

2. run shadowsocks server `go-shadowsocks2 -verbose -s "ss://chacha20-ietf-poly1305:hellotheworld4@[0.0.0.0]:1025" -udp`

3. run shadowsocks tunnek `go-shadowsocks2 -c 'ss://chacha20-ietf-poly1305:hellotheworld4@[0.0.0.0]:1025' -tcptun :1090=localhost:5201 -udptun :1090=localhost:5201  -verbose`

4. use iperf3 clinet to test udp `iperf3 -c 0.0.0.0 -p 1090 -u`

5. you can see the error log

**Expected behavior**

iperf3 test success

**Screenshots**

<img width="1085" alt="截屏2020-12-11 上午7 24 20" src="https://user-images.githubusercontent.com/24697284/101841951-f5777a00-3b81-11eb-86c0-c3707a045f19.png">

anyone could help? thanks

**Comment by Tigerfyj** [comment]
In the step 4, you should use the "localhost" as the address.
`iperf3 -c localhost -p 1090 -u`
