### ISSUE TITLE
Load Balancing

### ISSUE THREAD

**Issue by opsoyo** [shadowsocks/go-shadowsocks2#193]
**Is your feature request related to a problem? Please describe.**
With the [Windows Shadowsocks](https://github.com/shadowsocks/shadowsocks-windows) client, you can load balance several proxies instead of only chaining them together.

**Describe the solution you'd like**
It would be nice to have a load balancing feature that could appear in a few ways:
- Round robin
- Random choice
- Least used
- Lowest latency / highest availability 

**Describe alternatives you've considered**
Alternatively, multiple instances of go-shadowsocks2 could be run and load balanced by Nginx/etc, but I find that an inefficient use of resources and needlessly complex if this can be accomplished within one application.

**Comment by cn4** [comment]
Maybe you can have a look at [gost](https://github.com/ginuerzh/gost) of [glider](https://github.com/nadoo/glider)

**Comment by opsoyo** [comment]
> Maybe you can have a look at [gost](https://github.com/ginuerzh/gost) or [glider](https://github.com/nadoo/glider).

Perfect. Thank you.
