### ISSUE TITLE
tcp.go:65: failed to get target address: SOCKS error: 8

### ISSUE THREAD

**Issue by shuidaan** [shadowsocks/go-shadowsocks2#197]
**Describe the bug**

**To Reproduce**
 
![image](https://user-images.githubusercontent.com/24624971/105275866-2912de80-5bdb-11eb-869d-c8b55efe97d9.png)

**Expected behavior**
shadowsocks2 -c "ss://AEAD_CHACHA20_POLY1305:your-password@server_ip:18688"  -verbose -socks :1080 -u -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53  -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53

**Screenshots**
![image](https://user-images.githubusercontent.com/24624971/105276097-91fa5680-5bdb-11eb-914d-a7f3475ca279.png)
**Desktop (please complete the following information):**
 - OS: windows7
 - Browser chrome
 - Version  87.0.4280.141

 

**Additional context**

客户端不能正常上网，浏览器已经设置了代理模式
The client can't access the Internet normally，
The browser has set proxy mode

**Comment by threewater2** [comment]
i think it is because windows 10's system proxy only support http proxy, not support socks proxy .
if you want to test , i think you can use `curl`
like this :
`curl -x socks5://127.0.0.1:1080 http://www.google.com`
