### ISSUE TITLE
master code build error

### ISSUE THREAD

**Issue by zhoubowen-sky** [shadowsocks/go-shadowsocks2#205]
**Describe the bug**
run go get -u -v github.com/shadowsocks/go-shadowsocks2 error:

go/src/github.com/shadowsocks/go-shadowsocks2/tcp.go:159:37: undefined: os.ErrDeadlineExceeded
go/src/github.com/shadowsocks/go-shadowsocks2/tcp.go:162:35: undefined: os.ErrDeadlineExceeded

[root@VM-0-2-centos ~]# go version
go version go1.14.12 linux/amd64

**Comment by riobard** [comment]
https://github.com/shadowsocks/go-shadowsocks2/blob/master/go.mod
