### ISSUE TITLE
有段代码没看明白，为什么copy完了要setReadDeadLine

### ISSUE THREAD

**Issue by happymop977** [shadowsocks/go-shadowsocks2#215]
https://github.com/shadowsocks/go-shadowsocks2/blob/master/tcp.go#L157 
154 和157行，
后续代码里对left和right都木有read操作了，为什么要这么写呢，谢谢老板

**Comment by dev4u** [comment]
已经写了注释：`unblock read on *`

**Comment by happymop977** [comment]
谢谢老板
