### ISSUE TITLE
如何go run ？

### ISSUE THREAD

**Issue by jinchengWishes** [shadowsocks/go-shadowsocks2#228]
有知道的小伙伴晓得怎么run这项目，编译出来可以正常运行。我想直接go run 就运行不起来了。

**Comment by donghaoahahahah** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jinchengWishes** [comment]
0
