### ISSUE TITLE
It was not listening in UDP

### ISSUE THREAD

**Issue by http600** [shadowsocks/go-shadowsocks2#229]
Start shadowsocks in `nohup /home/work/workspace/go-shadowsocks2/go-shadowsocks2 -s 'ss://AEAD_CHACHA20_POLY1305:XYZ@:1236' -plugin /home/work/workspace/v2ray-plugin/v2ray-plugin -plugin-opts "server" &`

It was listening `1236` in TCP
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/72820259/164963291-3e233ad4-094a-45b4-af64-a341b7c0db61.png">

How to make it to listen UDP

**Comment by dev4u** [comment]
可以通过-h参数找到你要的信息。
