### ISSUE TITLE
Xchacha20 support?

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/go-shadowsocks2#23]
Is there any plan to support Xchacha20?

**Comment by riobard** [comment]
Currently no plan to do so. Which other SS implementation supports xchacha20?

**Comment by simonsmh** [comment]
All projects based on libsodium I think…

Rio <notifications@github.com>于2017年3月22日周三 23:30写道：

**Comment by riobard** [comment]
Any SS client supporting xchacha20?

**Comment by simonsmh** [comment]
some of the ss-libev based client?
And ss-android is going to have it in the next release according to their
commits.

Rio <notifications@github.com>于2017年3月23日周四 00:15写道：

**Comment by riobard** [comment]
Closed by #26

**Comment by simonsmh** [comment]
Shouldn't it be an AEAD cipher?
And its name is xchacha20-ietf-poly1305 according to shadowsocks.org

**Comment by riobard** [comment]
Xchacha20 and Xchacha20-ietf-poly1305 are completely different.

Also, the SS spec only requires AEAD_CHACHA20_POLY1305 as defined in RFC7539. The xchacha20-ietf-poly1305 variant is non-standard and won't be supported. It does not provide any additional security benefit anyway.
