### ISSUE TITLE
Not forwarding UDP

### ISSUE THREAD

**Issue by saeziae** [shadowsocks/go-shadowsocks2#235]
**Describe the bug**
Both server and client cannot forward UDP

**To Reproduce**
1. start a ss-go server and a ss-go client with `-u`
1. make a DNS request via proxy
1. timeout

It also happens on Go client with other server:
1. start a ss-rust server with `tcp_and_udp` and a ss-go client with `-u` 
1. make a DNS request via proxy
1. timeout

**Expected behavior**
UDP forwarded by ss

**Platform**
Linux amd64 and aarch64

**Comment by riobard** [comment]
Wrong repo.
