### ISSUE TITLE
DNS Leak and udptun/tcptun

### ISSUE THREAD

**Issue by SquirrelCoder** [shadowsocks/go-shadowsocks2#24]
Hi,

thanks a lot for this outstanding implementation.
The only way I can connect to my Shadowsocks-libev server is using this command:
`-c ss://AEAD_CHACHA20_POLY1305:PASSWORD@XXX:SERVER_PORT -verbose -socks :LOCAL_PORT`
after adding this line:
`-udptun :8053=8.8.8.8:53,:8054=8.8.4.4: -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53`
I can no longer open pages.
What does this line do? and where do I have to enter the two ports 8053 and 8054?
And another problem is I have DNS Leak, some websites, like Facebook, and Twitter return another IP, (not the actual IP - hence DNS Leak).

VPS (OpenVZ): CentOS 7 running Shadowsocks-libev
Client: Windows 10
Connecting using CMD.

Thanks a lot.

**Comment by riobard** [comment]
Did you enable UDP relay mode on the server? The UDP and TCP tunnels allow you to send DNS queries to Google DNS. You can try `dig @127.0.01 -p 8053 twitter.com` to see if it works.

**Comment by SquirrelCoder** [comment]
@riobard I don't think so. Could you please guide me, how can I enable UDP/TCP relay?
when I run the command:

`dig @127.0.01 -p 8053 twitter.com
`
on the CentOS server, I get the following output:

```
[root@test]# dig @127.0.01 -p 8053 twitter.com

; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> @127.0.01 -p 8053 twitter.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by riobard** [comment]
Should be `@127.0.0.1`. Sorry for the typo.

**Comment by SquirrelCoder** [comment]
still the same: 

```
; <<>> DiG 9.9.4-RedHat-9.9.4-38.el7_3.2 <<>> @127.0.0.1 -p 8053 twitter.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by riobard** [comment]
Try `dig @127.0.0.1 -p 8053 +tcp twitter.com`

**Comment by SquirrelCoder** [comment]
almost immediately got the following output: 

`;; Connection to 127.0.0.1#8053(127.0.0.1) for twitter.com failed: connection refused.`

**Comment by SquirrelCoder** [comment]
Shadowsocks-libev service in ` /usr/lib/systemd/system/shadowsocks-libev.service` 
looks like this in my VPS:

```
[Unit]
Description=Shadowsocks-libev Default Server Service
Documentation=man:shadowsocks-libev(8)
After=network.target

[Service]
Type=simple
EnvironmentFile=/etc/default/shadowsocks-libev
User=root
LimitNOFILE=32768
#ExecStart=/usr/bin/ss-server -a $USER -c $CONFFILE $DAEMON_ARGS
ExecStart=/usr/bin/ss-manager --manager  127.0.0.1:59990 --executable /usr/bin/ss-server -v -c /etc/shadowsocks-libev/config.json
[Install]
WantedBy=multi-user.target
```

**Comment by SquirrelCoder** [comment]
my `config.json` file, is multi-user, don't know if this information helps, thanks a lot :)

**Comment by riobard** [comment]
Maybe you could try to run go-shadowsocks2 on the server and see what's wrong.

**Comment by SquirrelCoder** [comment]
thanks for the reply. Tried with `go-shadowsocks2`, everything works perfectly, but still, some sites, like YouTube won't open. 
This is the error on the terminal on VPS:
```
2017/03/14 11:30:18 failed to connect to target: dial tcp [THAT_CENSORED_IP]:80: getsockopt: connection timed

**Comment by riobard** [comment]
Looks like your DNS is poisoned. Point your DNS server to 127.0.0.1:8053

**Comment by SquirrelCoder** [comment]
yup they are, but how can I point my DNS server to `127.0.0.1:8053`?

**Comment by riobard** [comment]
That depends on your OS.

**Comment by SquirrelCoder** [comment]
Server: CentOS 7 OpenVZ
Client: Windows 10 x64

**Comment by riobard** [comment]
No idea how it works on Windows. You might want to Google for it.

**Comment by nadoo** [comment]
@SquirrelCoder 
try: https://github.com/nadoo/glider
glider -l :8443 -l dnstun://:8053=8.8.8.8:53 -v -f ss://AEAD_CHACHA20_POLY1305:PASSWORD@XXX:SERVER_PORT
will serve udp dns requests and forward to remote ss server via tcp

**Comment by SquirrelCoder** [comment]
@nadoo Thanks a lot man. Greatly appriciate it. Will definitely try it out :).
