### ISSUE TITLE
问下可以编译成Android 的so 动态库吗

### ISSUE THREAD

**Issue by longkehuawei** [shadowsocks/go-shadowsocks2#240]
问下可以编译成Android 的so 动态库吗

**Comment by donghaoahahahah** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by qwe7002** [comment]
可以用gomobile编译，通过gomodule引入之后，把main.go中对应的方法重新封装一下就行了
