### ISSUE TITLE
tcp.go:67: failed to get target address: SOCKS error: 8 

### ISSUE THREAD

**Issue by houxinlin** [shadowsocks/go-shadowsocks2#246]
The server is ubuntu, and I'm running on the client (my client is manjaro). I got this error by setting the proxy address 127.0.0.1:1080 through the system

**Comment by chenyu1990** [comment]
`export http_proxy=socks5://127.0.0.1:1080
export https_proxy=socks5://127.0.0.1:1080`

**Comment by MrDkVV** [comment]
How was this fixed? 

Changing poxy config on the host, should and had no effect on the results?

export http_proxy=socks5://192.168.12.3:12345
export https_proxy=socks5://192.168.12.3:12345
