### ISSUE TITLE
运行时报：panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by yjsslab** [shadowsocks/go-shadowsocks2#25]
github.com/shadowsocks/go-shadowsocks2/socks.Addr.String(0x188d9680, 0x2, 0x103, 0x2, 0x103)

**Comment by riobard** [comment]
需要整个 panic 的  log

**Comment by yjsslab** [comment]
@riobard 当时只把这行复制了下来，在console下其它被清了，要不加个 logfile 功能。到现在没报了，比较难重现。

**Comment by riobard** [comment]
可以重定向 stderr 到文件实现 logfile 功能，不需要单独加。
