### ISSUE TITLE
使用方法希望改进

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/go-shadowsocks2#28]
感觉命令和其他ss版本差距太大，具体怎么使用还是没看懂，为什么不推出配置文件夹在的方法？还有顺便问下TFO什么时候推出？

**Comment by riobard** [comment]
TCP Fast Open will be supported in Go 1.9 https://github.com/golang/go/issues/4842

**Comment by shoyuf** [comment]
TFO can support in current version?

**Comment by riobard** [comment]
Unfortunately Go still does not have official support for TFO yet. See the above link to golang.

**Comment by frustreated** [comment]
可能是我太笨了，也是没看太明白。
