### ISSUE TITLE
How to use simple-obfs plugin in windows?

### ISSUE THREAD

**Issue by juneszh** [shadowsocks/go-shadowsocks2#31]
In windows, I find this go2 is the only client that support AEAD. Is it also support simple-obfs ？

**Comment by riobard** [comment]
You can use the simple-obfs plugin in standalone mode.

**Comment by suikatomoki** [comment]
Sure,and you need build simple-obfs with cygwin.Or you can use this: https://cokebar.info/archives/1988

**Comment by xqdoo00o** [comment]
Now the C-sharp has been updated to support AEAD.

**Comment by juneszh** [comment]
thx a lot!
