### ISSUE TITLE
Which license does this project use?

### ISSUE THREAD

**Issue by hellofwy** [shadowsocks/go-shadowsocks2#33]

**Comment by riobard** [comment]
Haven't decided yet. Any suggestions?

**Comment by hellofwy** [comment]
I don't think it's up to me. 
Golang itself is using BSD-sytle license. But it still depends on your insight about this project.

**Comment by riobard** [comment]
Personally my attitude is generally "do whatever you want and don't sue me". The original shadowsocks seems to use Apache License v2.0. I guess it's easier to stick with that one?

**Comment by hellofwy** [comment]
Found a page: https://choosealicense.com/appendix/

Putting it in public domain may be most unrestricted.

**Comment by riobard** [comment]
Fixed via c5b731a52845fec583653d0c962a5802a8a9baff
