### ISSUE TITLE
Is that possible to give some instructions/guides on how to setup iptable rules for Netfilter TCP redirect?

### ISSUE THREAD

**Issue by sgon00** [shadowsocks/go-shadowsocks2#36]
Is that possible to give some instructions/guides on how to setup iptable rules for Netfilter TCP redirect?
I plan to make a router based on debian. (there are many online tutorials/docs about how to do this). I would like to know how to setup iptable rules to use go-shadowsocks2 on this debian router. similar to openwrt version shadowsocks-libev: Route non-china IPs (IPs not in ignore.list) through go-shadowsocks2. I am new to iptables and wondering if it's possible to get some instructions. Thank you very much.

**Comment by riobard** [comment]
The instructions are the same as the one used for shadowsocks-libev https://github.com/shadowsocks/shadowsocks-libev
