### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/go-shadowsocks2#38]
I found that the io.Copy(left, right) can be blocked. So the tcp connection will not be released. Have you found that?@riobard

**Comment by arthurkiller** [comment]
> right.SetDeadline(time.Now()) // wake up the other goroutine blocking on right

This also confused me. How could this Wake up another goroutine?

**Comment by riobard** [comment]
What do you expect `io.Copy` is supposed to work until an error is encountered. `SetDeadline` will trigger an error to interrupt the goroutine blocking on `in.Copy`.

**Comment by arthurkiller** [comment]
@riobard Yeap, but that's not the correct way closing a connection I think. Read until the __EOF__ occoured, that should be that point.

What confused me alot is that why we can not get the __EOF__ from a tcp connection.
See the code below

``` golang
|   for {
|   |   nr, er := src.Read(buf)
|   |   if nr > 0 {
|   |   |   nw, ew := dst.Write(buf[0:nr])
|   |   |   if nw > 0 {
|   |   |   |   written += int64(nw)
|   |   |   }
|   |   |   if ew != nil {
|   |   |   |   err = ew
|   |   |   |   break
|   |   |   }
|   |   |   if nr != nw {
|   |   |   |   err = ErrShortWrite
|   |   |   |   break
|   |   |   }
|   |   }
|   |   if er != nil {
|   |   |   if er != EOF {
|   |   |   |   err = er
|   |   |   }
|   |   |   break
|   |   }
|   }
```

that's the code in __io.Copy__ , so we should expect Read the __EOF__ but not the timeout

**Comment by arthurkiller** [comment]
I think in-comming connection should be closed by us, but the out-going connection should be closed after EOF, right?

**Comment by riobard** [comment]
`io.Copy` will return when read hits EOF, so the connection will be closed correctly. I don't see any problems here. The proxy manages a pair of connections, and the other connection does not have an EOF condition. You have to unblock the other goroutine by triggering a timeout error.

**Comment by bigtan** [comment]
fixed through https://github.com/riobard/go-shadowsocks2/pull/8
