### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by zzuzjl** [shadowsocks/go-shadowsocks2#39]
能不能像go版一样提供二进制预编译好的服务器版啊，很有用啊。

**Comment by riobard** [comment]
Experimental pre-releases are available at https://github.com/riobard/go-shadowsocks2/releases

**Comment by zzuzjl** [comment]
用上了，不错，谢谢

**Comment by zzuzjl** [comment]
测试有个问题，就是chacha20-ietf-poly1305加密方式在ios上的Cross应用上不能正常使用（使shadowsocks-libev和shadowsocks-perl服务器端搭建的没有问题），不知道什么原因

**Comment by riobard** [comment]
Insufficient information to debug.

**Comment by zzuzjl** [comment]
@riobard 我不知道怎么看信息，我说一下具体问题，我在vps上使用预编译好的文件，搭建的服务器端，在电脑上可以正常使用，在ios上使用Cross和shadowrocket上都不能用，而同一vps上使用shadowsocks-libev和shadowsocks-perl服务器端搭建的都可以在Cross和shadowrocket上正常使用。

**Comment by riobard** [comment]
Which client do you use on PC?

**Comment by zzuzjl** [comment]
@riobard https://github.com/shadowsocks/shadowsocks-windows/releases电脑上是这个，可以正常使用

**Comment by zzuzjl** [comment]
@riobard 大神找到原因了吗？

**Comment by riobard** [comment]
试一下新的版本 https://github.com/riobard/go-shadowsocks2/releases/tag/v0.0.9

**Comment by zzuzjl** [comment]
@riobard 感谢更新，新版已经可以正常使用了，比起其他版本这个预编译好的二进制版本更简单易用适合低内存vps和没有root权限的vps。
