### ISSUE TITLE
Please do not support HTTP proxy

### ISSUE THREAD

**Issue by icreata** [shadowsocks/go-shadowsocks2#41]
I'm actually addressing an outstanding issue: https://github.com/shadowsocks/go-shadowsocks2/issues/27 (Feature Request: HTTP proxy)

Based on my experience with Android, https://play.google.com/store/apps/details?id=com.github.shadowsocks covers every need on a per app basis. So there is no need for HTTP proxy Android platform.

On Windows and Linux systems, there is the excellent privoxy. It can server as a HTTP proxy and connect upstream to go-shadowsocks2. In fact, some windows shadowsocks client come with privoxy bundled to alleviate the need for HTTP proxy. Anyone who is smart enough to know how good go-shadowsocks2 is should also be smart enough to configure and use privoxy, right?

Personally, I'd like to see go-shadowsocks2 maintain its edge in providing cutting-edge shadowsocks feature, such as support for latest cryptos. I am very happy to say that I very impressed by the fact that when I uploaded the some 2MB go-shadowsocks2.exe to a nano server, it just worked as a server (in addition to being a client) and supported AEAD_CHACHA20_POLY1305.

My appreciations to the developer(s)!

**Comment by bigtan** [comment]
https://github.com/bigtan/cow  

I wrote a http and socks client based on go-ss2

**Comment by elico** [comment]
@icreata What is the issue with supporting http proxy?
I really don't get what and why you oppose to it.
