### ISSUE TITLE
cipher not supported

### ISSUE THREAD

**Issue by tiliarou** [shadowsocks/go-shadowsocks2#43]
Windows 10 1607, x64 anniversary update.
Go installed today 1.8.1
Git installed today
go-shadowsocks2 from today

I just changed my server IP and password, and copy paste the command indicated in readme, i.e. using default cipher:
`go-shadowsocks2 -c ss://AEAD_CHACHA20_POLY1305:password@89.40.xxx.xxx:8xxx -verbose -socks :1080 -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53
`
Gives me error: `cipher not supported`

**Comment by riobard** [comment]
Could you try pre-compiled binary from https://github.com/riobard/go-shadowsocks2/releases and see if the problem persists?

**Comment by damoye** [comment]
I've been in this situation too. My condition is that my password has special character "@" in it, which is a special character in URL. So I used "-password" to input my password and it worked.

**Comment by riobard** [comment]
@damoye You should quote your password if it contains special characters.
