### ISSUE TITLE
一些有关 Shadowsocks 的想法，应该具备下面特性

### ISSUE THREAD

**Issue by zyfdegh** [shadowsocks/go-shadowsocks2#46]
看到很多 Shadowsocks 的实现，但基本架构没有变。
仍然是中心化的，一个服务端，一个或多个客户端。

要么就实现了负载均衡，服务端有多个 ss server，对外一个访问地址。
但这仍是中心化的。

这存在一些弊端：

1. 由于中心化，个人自建 ss 昂贵，合租又麻烦；
2. 由于中心化，组织创建的提供 ss 帐号的网站，声势大了会被当局整治，尤其是在新网络安全法生效后，监管将更加严格；
3. 配置繁琐，而且不能一劳永逸。

最近在看 Bitcoin（区块链） 的架构，受到一些启发，在想是否能够实现一套具备下面特征的 ss 网络。

1. 分布式（防止被当局一锅端）；
2. P2P（加入网络即可，无需复杂服务端客户端配置，小白和女友都会）；
3. 节点之间互信互联，传输仍然加密；
4. 匿名的（相当于具备了 Tor 网路）；
5. 费用？能翻墙的赚钱，贡献多赚的多；需要翻墙的花钱，用的多花的多。

我想，这样的 ss 可以称作 Next-generation Shadowsocks 吧。

个人认知有限，轻喷！

**Comment by Teddysun** [comment]
相当于 Tor，那为什么不优化 Tor，让更多的人知道 Tor 的存在，让更多的人更简单的使用 Tor 呢（逃

**Comment by theratlesnake** [comment]
@Teddysun  大神說得對

**Comment by douyaolai** [comment]
我好奇的是有没有类似discuz的程序

**Comment by fuyufjh** [comment]
Please remember to always keep it very secret and private if you want to use shadowsocks for next years. I am serious.

**Comment by jicki** [comment]
Shadowsocks 的存在不是只为了让你翻墙使用的！！

**Comment by baoang** [comment]
不是有个叫ZeroNET的东西么？
