### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by azgh** [shadowsocks/go-shadowsocks2#47]
运行
`go get -u -v github.com/shadowsocks/go-shadowsocks2`
后，运行
`go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:***@:*** -verbose`
显示
`-bash: go-shadowsocks2: command not found`
请帮忙，谢谢！

**Comment by nadoo** [comment]
%GOPATH%\bin 要加入 PATH 变量

**Comment by azgh** [comment]
@nadoo 运行`go get -u -v github.com/shadowsocks/go-shadowsocks2`就需要设置环境变量了，否则无法运行，按照提示设置环境变量后，`go get -u -v github.com/shadowsocks/go-shadowsocks2`运行成功，但执行`go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:***@:*** -verbose`出现`-bash: go-shadowsocks2: command not found`提示，难道环境变量设置的不对？
debian8要怎样设置呢？多谢解答🙏

**Comment by jadeydi** [comment]
是环境变量不对 go install 试试，前题是你的 GOPATH 加到环境变量里了，要么用相对路径试试，比如 ./go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:***@:*** -verbose

**Comment by chinsyo** [comment]
可以尝试使用可执行文件的绝对路径，即 GOPATH 下 bin 目录的 go-shadowsocks2。
