### ISSUE TITLE
Use as a library?

### ISSUE THREAD

**Issue by maddie** [shadowsocks/go-shadowsocks2#48]
Currently the project seems to have most of its functions unexported, so it's quite difficult to use it as a library (embed into another project).

Are there any plans on this?

**Comment by maddie** [comment]
Hmm.. on a second thought, this shouldn't be something that worries you. I'll close this for now.

**Comment by riobard** [comment]
All necessary functions are exported. See https://godoc.org/github.com/shadowsocks/go-shadowsocks2

**Comment by maddie** [comment]
@riobard Thanks. I got it figured out :)
