### ISSUE TITLE
failed to get target address: cipher: message authentication failed

### ISSUE THREAD

**Issue by netroby** [shadowsocks/go-shadowsocks2#50]
May 21 00:43:30 vultr.guest go-shadowsocks2[14381]: 2017/05/21 00:43:30 failed to get target address: cipher: message authentication failed
May 21 00:43:31 vultr.guest go-shadowsocks2[14381]: 2017/05/21 00:43:31 failed to get target address: EOF

**Comment by riobard** [comment]
Insufficient information to reproduce.

**Comment by chenyangguang** [comment]
➜  bin ./go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:my-pwd@:9999 -verbose
2017/11/26 09:26:32 listening UDP on :9999
2017/11/26 09:26:32 listening TCP on :9999

                                                                                                                                                                     ➜  bin ./go-shadowsocks2 -c ss://AEAD_CHACHA20_POLY1305:my-pwd@[my-ip]:9999 \
     -verbose -socks :1080 -u -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 \
                              -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53

appear:  
**2017/11/26 09:34:13 failed to get target address: SOCKS error: 7**

**Comment by riobard** [comment]
Should be fixed by #79
