### ISSUE TITLE
Please support udp relay like shadowsocks-libev

### ISSUE THREAD

**Issue by netroby** [shadowsocks/go-shadowsocks2#53]
would you please support shadowsocks-libev 's udp relay?

**Comment by riobard** [comment]
I might not have time to implement it. A pull request would be very welcome :)

**Comment by choleraehyq** [comment]
Hi, I've read `udp.go` in this repo and `udprelay.go` in `shadowsocks-go`, it seems that what `udpRemote` do is exactly udp relay, am I miss something?

**Comment by lixin9311** [comment]
Closed by https://github.com/shadowsocks/go-shadowsocks2/pull/71
