### ISSUE TITLE
go get failed.

### ISSUE THREAD

**Issue by finomxf** [shadowsocks/go-shadowsocks2#55]
fino@cts-154:~$ go get -u -v github.com/shadowsocks/go-shadowsocks2
github.com/shadowsocks/go-shadowsocks2 (download)
Fetching https://golang.org/x/crypto/chacha20poly1305?go-get=1
https fetch failed: Get https://golang.org/x/crypto/chacha20poly1305?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/crypto/chacha20poly1305: unrecognized import path "golang.org/x/crypto/chacha20poly1305" (https fetch: Get https://golang.org/x/crypto/chacha20poly1305?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Fetching https://golang.org/x/crypto/hkdf?go-get=1
https fetch failed: Get https://golang.org/x/crypto/hkdf?go-get=1: dial tcp 216.239.37.1:443: i/o timeout
package golang.org/x/crypto/hkdf: unrecognized import path "golang.org/x/crypto/hkdf" (https fetch: Get https://golang.org/x/crypto/hkdf?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
github.com/Yawning/chacha20 (download)

################################################################################
it seems golang.org/x/crypto is not there, 
my PC is ubuntu 14.04, go version is 1.8.3,  1 month ago when I just installed go-shadowsocks2 on my server and it works fine.   any one meet the same issue? 

BR fino

**Comment by riobard** [comment]
golang.org is GFW'ed.

**Comment by lixiang4u** [comment]
@riobard  i have connected vpn globally,but failed to get [golang.org/x/crypto/chacha20poly1305](golang.org/x/crypto/chacha20poly1305),it says:

> package golang.org/x/crypto/chacha20poly1305: unrecognized import path "golang.org/x/crypto/chacha20poly1305" (https fetch: Get https://golang.org/x/crypto/chacha20poly1305?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
