### ISSUE TITLE
kcpserver & kcplocal

### ISSUE THREAD

**Issue by bradyjoestar** [shadowsocks/go-shadowsocks2#57]
I wanna to implement the kcpserver and kcplocal to  use the kcp protocal more easily by using kcp-go.I wonder if I can add this feature to the project?  :D

**Comment by riobard** [comment]
What do you mean? I thought KCP can be used right now by connecting the corresponding server and local components.

**Comment by bradyjoestar** [comment]
I want to migrate the go-shadowsocks2 and kcptun so that is more friendly to beginners.
It sounds like redundant,anybody who  use go-ss2  can easily use kcptun as they want.
I got it.
