### ISSUE TITLE
[建议]需要翻墙的某些import方式能否修改下

### ISSUE THREAD

**Issue by AnotherGoogleFan** [shadowsocks/go-shadowsocks2#58]
项目内用到了几个golang.org的包。
因为众所周知的原因，国内访问不了。
这就会陷入死循环，来弄shadowsocks就是为了翻墙，然而要弄shadowsocks就需要先翻墙才能拉下来相应的包……
幸好golang官方在github上做了mirror。建议采用mirror方式。
比如，用 github.com/golang/crypto 代替 golang.org/x/crypto，这样的话只要github还活着就不会遇见类似的问题。

**Comment by septs** [comment]
@riobard 我觉得或许可以在 releases 发布预编译的二进制

**Comment by riobard** [comment]
@septs https://github.com/riobard/go-shadowsocks2/releases

**Comment by riobard** [comment]
`github.com/golang/crypto` cannot be imported due to canonical import path. If you have problems accessing `golang.org`, you should manually clone the mirror into `$GOPATH`. 

In the future we might consider vendoring dependencies.
