### ISSUE TITLE
obfu plugin interface

### ISSUE THREAD

**Issue by septs** [shadowsocks/go-shadowsocks2#6]
you want to export one such interface

type ObfuPlugin func (conn net.Conn) (obfsConn net.Conn, err error)

see https://github.com/shadowsocks/shadowsocks-org/issues/28

**Comment by riobard** [comment]
Not really. 

According to SIP003, pluggins are supposed to run as another process, and not necessarily implemented in Go. You should change the listening/connecting port instead.
