### ISSUE TITLE
how to integrate?

### ISSUE THREAD

**Issue by septs** [shadowsocks/go-shadowsocks2#7]
continue riobard/go-shadowsocks2#1

**Comment by riobard** [comment]
@septs Do you think you can work with the changes introduced here https://github.com/riobard/go-shadowsocks2/commit/3e9aaf3caad95ee55f550cd01c52946705df72a6 ? 

I've moved all cipher-related code to core.

**Comment by septs** [comment]
thx

**Comment by riobard** [comment]
Now merged into https://github.com/shadowsocks/go-shadowsocks2 

Let me know if there's any problem.
