### ISSUE TITLE
Error: failed to get target address: SOCKS error: 7

### ISSUE THREAD

**Issue by chenhw2** [shadowsocks/go-shadowsocks2#72]
Ver: https://github.com/shadowsocks/go-shadowsocks2/commit/c2e771073ec068cc8a7eab54c2f2bb77ee5d472d

Server 
```go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:TEST@:8088 -verbose```

Client 
```go-shadowsocks2 -c ss://AEAD_CHACHA20_POLY1305:TEST@[SERVER]:8088 -verbose -u -socks :2000```

Test
```curl --socks5-hostname 127.0.0.1:2000 ip.gs```

Error
curl: ```curl: (7) Failed to receive SOCKS5 connect request ack.```
server:  ```failed to get target address: SOCKS error: 7```

**Comment by mohuishou** [comment]
要到了相同的错误，自己改了
https://github.com/shadowsocks/go-shadowsocks2/pull/79

**Comment by riobard** [comment]
Fixed by #79
