### ISSUE TITLE
获取不到主机ip地址，这个是怎么回事？

### ISSUE THREAD

**Issue by chenyangguang** [shadowsocks/go-shadowsocks2#78]
`./go-shadowsocks2` -s ss://AEAD_CHACHA20_POLY1305:my-pwd@:9999 -verbose
2017/11/26 09:26:32 listening UDP on :9999
2017/11/26 09:26:32 listening TCP on :9999

```
 ./go-shadowsocks2 -c ss://AEAD_CHACHA20_POLY1305:my-pwd@[my-ip]:9999 \
     -verbose -socks :1080 -u -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 \
                              -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53
```
报这个反馈:
2017/11/26 09:34:13 failed to get target address: SOCKS error: 7

查了源码出处是这里报的错误：　
**tcp.go** 文件下面第63行的　`tcpLocal()`方法中　调用了**getAddr(c)**这个地方产生的 err 错误. 
`logf("failed to get target address: %v", err)`

**Comment by mohuishou** [comment]
遇到了相同的错误，自己改了

**Comment by chenyangguang** [comment]
@mohuishou 你怎么改的？有记录？
