### ISSUE TITLE
what is the difference between shadowsocks-go and go-shadowsocks2?

### ISSUE THREAD

**Issue by yydcool** [shadowsocks/go-shadowsocks2#8]
Please write something in the readme.
Thanks.

**Comment by yydcool** [comment]
The code base strives to

be idiomatic Go and well organized;
use fewer external dependences as reasonably possible;
only include proven modern ciphers;

**Comment by riobard** [comment]
`shadowsocks-go` does not support the latest AEAD ciphers.
