### ISSUE TITLE
No matches found: ss://AEAD_CHACHA20_POLY1305:XXXXXXXX@[serv-ip]:8488

### ISSUE THREAD

**Issue by chenyangguang** [shadowsocks/go-shadowsocks2#84]
ubuntu16.04
go1.10 linux/amd64

➜  bin ./go-shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:password@:8488 -verbose
2018/04/03 23:08:36 listening TCP on :8488
2018/04/03 23:08:36 listening UDP on :8488

➜  bin ./go-shadowsocks2 -c ss://AEAD_CHACHA20_POLY1305:password@[serv-ip]:8488 \
     -verbose -socks :1080 -u -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 \
                              -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53

zsh: no matches found: ss://AEAD_CHACHA20_POLY1305:password@[serv-ip]:8488

**Comment by riobard** [comment]
Quote your password to prevent zsh expansion of `*` and `?`.
