### ISSUE TITLE
failed to get target address: EOF

### ISSUE THREAD

**Issue by xiaoxing598** [shadowsocks/go-shadowsocks2#85]
The following error occurs when linking SS service on Windows platform:

```bash
D:\tools>shadowsocks2-win64.exe -c ss://AEAD_CHACHA20_POLY1305:xxx@xx.xxx.xxx.xxx:18488 -socks :1080 -verbose
2018/04/08 10:23:06 SOCKS proxy :1080
2018/04/08 10:23:57 failed to get target address: EOF
2018/04/08 10:23:57 failed to get target address: EOF
2018/04/08 10:23:57 failed to get target address: EOF
2018/04/08 10:24:04 failed to get target address: EOF
2018/04/08 10:24:04 failed to get target address: EOF
2018/04/08 10:24:05 failed to get target address: EOF
2018/04/08 10:24:05 failed to get target address: EOF
2018/04/08 10:24:16 failed to get target address: EOF
```

The same connection statement works fine on my Mac and it is normal to try the Telnet SS service on this Windows.

**Comment by ericyoungChen** [comment]
The go-shadowsocks2 running on my VPS also has this problem, while i was try to access some site like instagram, the ss-client would lost connection ,the log shows like this:

	Apr 17 15:36:00 go-shadowsocks2[11613]: 2018/04/17 15:36:00 failed to get target address: SOCKS error: 8
	Apr 17 15:36:02 go-shadowsocks2[11613]: 2018/04/17 15:36:02 failed to get target address: SOCKS error: 8
	Apr 17 15:36:02 go-shadowsocks2[11613]: 2018/04/17 15:36:02 failed to get target address: SOCKS error: 8
	Apr 17 15:36:02 go-shadowsocks2[11613]: 2018/04/17 15:36:02 failed to get target address: SOCKS error: 8
	Apr 17 15:36:02 go-shadowsocks2[11613]: 2018/04/17 15:36:02 failed to get target address: SOCKS error: 8
	Apr 17 15:36:02 go-shadowsocks2[11613]: 2018/04/17 15:36:02 failed to get target address: SOCKS error: 8
	Apr 17 15:36:03 go-shadowsocks2[11613]: 2018/04/17 15:36:03 failed to get target address: SOCKS error: 8
	Apr 17 15:36:04 go-shadowsocks2[11613]: 2018/04/17 15:36:04 failed to get target address: SOCKS error: 8
	.
	.
	.
	.
	Apr 17 15:38:43 go-shadowsocks2[11613]: 2018/04/17 15:38:43 failed to get target address: EOF
	Apr 17 15:38:43 go-shadowsocks2[11613]: 2018/04/17 15:38:43 failed to get target address: EOF

How to solve this problem???

**Comment by riobard** [comment]
Paste your detailed config.

**Comment by xiaoxing598** [comment]
Instead of using the command line connection on the Windows platform, the [client](https://github.com/shadowsocks/shadowsocks-windows/releases) is downloaded and everything is now normal.

![image](https://user-images.githubusercontent.com/5615719/38907004-35a12d42-42ec-11e8-9402-6f8e278f4979.png)

**Comment by riobard** [comment]
Does Windows support SOCKS proxy in the system settings? I thought it only supports HTTPS proxy.

**Comment by xiaoxing598** [comment]
The above method fully supports the SCOKET protocol and works well on my Windows computer.
If you just try it, you will know it. It is very simple and good luck!

**Comment by riobard** [comment]
Good to know! 👍
