### ISSUE TITLE
Is it possible to use virtual tun device to redirect all traffic? 

### ISSUE THREAD

**Issue by Chenyao2333** [shadowsocks/go-shadowsocks2#89]
SS only supports TCP/UDP.

So go-shadowsocks2 can only redirect TCP/UDP traffic. Listening virtual tun device make it's easier to run it on the router.

**Comment by riobard** [comment]
That would be [shadowvpn](https://github.com/clowwindy/ShadowVPN), which comes with different set of tradeoffs. In most cases, TCP/UDP is all we need.
