### ISSUE TITLE
README的范例错误

### ISSUE THREAD

**Issue by caodianlong** [shadowsocks/go-shadowsocks2#92]
README的命令范例中url带引号启动报错， 不带引号才是正确的
错误： shadowsocks2 -s 'ss://AEAD_CHACHA20_POLY1305:your-password@:8488' -verbose
正确：shadowsocks2 -s ss://AEAD_CHACHA20_POLY1305:your-password@:8488 -verbose

**Comment by geek1011** [comment]
They are both correct. In general, it is better to use quotes to prevent the shell from misinterpreting the url.

**Comment by caodianlong** [comment]
发现在Linux下有没有引号都是正确的，在Windows下带引号是错误的
D:\GoWork\bin>go-shadowsocks2 -s 'ss://AEAD_CHACHA20_POLY1305:your-password@:8488' -verbose
url: 'ss://AEAD_CHACHA20_POLY1305:your-password@:8488'
2018/06/06 15:35:31 UDP remote listen error: listen udp: address 'ss://AEAD_CHACHA20_POLY1305:your-password@:8488': too many colons in address
2018/06/06 15:35:31 failed to listen on 'ss://AEAD_CHACHA20_POLY1305:your-password@:8488': listen tcp: address 'ss://AEAD_CHACHA20_POLY1305:your-password@:
: too many colons in address

**Comment by geek1011** [comment]
Double quotes should work on both Linux and Windows.

**Comment by riobard** [comment]
Windows users should figure out the convention of their platform.

**Comment by jejayhe** [comment]
在mac下也不能加引号
