### ISSUE TITLE
Is there a way to confuse traffic?

### ISSUE THREAD

**Issue by xiaoxing598** [shadowsocks/go-shadowsocks2#93]
I purchased the server on site [bandwagonhost](https://bandwagonhost.com). After installing `go-shadowsocks2`, I was able to satisfy the traffic forwarding, but it was soon closed.

Now I need to change the IP by switching rooms. This kind of work is too much for me. I am looking for ways to confuse traffic.

**Comment by riobard** [comment]
Use an obfs plugin.

**Comment by xiaoxing598** [comment]
@riobard Can provide some `go-shadowsocks2` example, thank you very much!

**Comment by xiaoxing598** [comment]
thanks! @riobard
