### ISSUE TITLE
buffer overlap in packet decryption

### ISSUE THREAD

**Issue by lixin9311** [shadowsocks/go-shadowsocks2#95]
https://github.com/shadowsocks/go-shadowsocks2/blob/master/shadowstream/packet.go#L42

according to https://golang.org/pkg/crypto/cipher/#Stream
```
        // XORKeyStream XORs each byte in the given slice with a byte from the
        // cipher's key stream. Dst and src must overlap entirely or not at all.
```
in go 1.11, they have introduced a overlap checking before XORKeyStream, even it may work and behave normal before go 1.11, but the program will panic in go 1.11+.

see:
https://github.com/golang/go/blob/master/src/crypto/cipher/cfb.go#L24
and
https://github.com/golang/go/blob/master/src/crypto/internal/subtle/aliasing.go#L29

**Comment by riobard** [comment]
Too bad we have to use mutex and another buffer in the read path… Do you mind sending a PR to fix this?

**Comment by riobard** [comment]
https://github.com/shadowsocks/go-shadowsocks2/blob/master/shadowaead/packet.go#L87 

I believe this is also affected, right?

**Comment by riobard** [comment]
Actually we could still avoid locking. Just decrypt into the same buffer and do a memory copy to move forward instead.

**Comment by lixin9311** [comment]
I think just add a read buffer like the Write() will fix this issue without
blocking.

**Comment by riobard** [comment]
You mean make a new buffer each time? That'll trash GC.

**Comment by lixin9311** [comment]
A new buffer each socket, like you already did as packetConn.buf.

**Comment by riobard** [comment]
Yeah, that was what I said in the first reply. But come to think about it, we could avoid it. Using shared buffer involves locking for goroutine-safety.

**Comment by lixin9311** [comment]
I think there is only 1 goroutine trying to read from a UDP socket at the same time, which happens inside it's read loop or timesCopy. It is safe to add a read buffer without locking.

**Comment by riobard** [comment]
See my review in the PR.
